#ifndef CIG_WIN95_DEMO_RESOURCE_ENUMS_INCLUDED
#define CIG_WIN95_DEMO_RESOURCE_ENUMS_INCLUDED

typedef enum {
  FONT_REGULAR = 0,
  FONT_BOLD,
  FONT_TIMES_NEW_ROMAN_32_BOLD,
  FONT_ARIAL_BLACK_32,
  FONT_FRANKLIN_GOTHIC_BOOK_32,
  __FONT_COUNT
} font_id_t;

typedef enum {
  COLOR_BLACK = 0,
  COLOR_WHITE,
  COLOR_YELLOW,
  COLOR_GREEN,
  COLOR_RED,
  COLOR_MAROON,
  COLOR_BLUE,
  COLOR_NAVY,
  COLOR_DESKTOP_BG,
  COLOR_DIALOG_BACKGROUND,
  COLOR_WINDOW_ACTIVE_TITLEBAR,
  COLOR_WINDOW_INACTIVE_TITLEBAR,
  COLOR_DEBUG,
  __COLOR_COUNT
} color_id_t;

typedef enum {
  IMAGE_BRIGHT_YELLOW_PATTERN = 0,
  IMAGE_GRAY_DITHER,
  IMAGE_START_ICON,
  IMAGE_LOGO_TEXT,
  IMAGE_START_SIDEBAR,
  IMAGE_MY_COMPUTER_16,
  IMAGE_MY_COMPUTER_32,
  IMAGE_TIP_OF_THE_DAY,
  IMAGE_CHECKMARK,
  IMAGE_CROSS,
  IMAGE_MAXIMIZE,
  IMAGE_MINIMIZE,
  IMAGE_RESTORE,
  IMAGE_SCROLL_UP,
  IMAGE_SCROLL_DOWN,
  IMAGE_SCROLL_LEFT,
  IMAGE_SCROLL_RIGHT,
  IMAGE_WELCOME_APP_ICON,
  IMAGE_BIN_EMPTY,
  IMAGE_BIN_EMPTY_16,
  IMAGE_DRIVE_A_16,
  IMAGE_DRIVE_A_32,
  IMAGE_DRIVE_C_16,
  IMAGE_DRIVE_C_32,
  IMAGE_DRIVE_D_16,
  IMAGE_DRIVE_D_32,
  IMAGE_CONTROLS_FOLDER_16,
  IMAGE_CONTROLS_FOLDER_32,
  IMAGE_PRINTERS_FOLDER_16,
  IMAGE_PRINTERS_FOLDER_32,
  IMAGE_DIAL_UP_FOLDER_16,
  IMAGE_DIAL_UP_FOLDER_32,
  IMAGE_RESIZE_HANDLE,
  IMAGE_MENU_CHECK,
  IMAGE_MENU_CHECK_INVERTED,
  IMAGE_MENU_RADIO,
  IMAGE_MENU_RADIO_INVERTED,
  IMAGE_MENU_ARROW,
  IMAGE_MENU_ARROW_INVERTED,
  IMAGE_PROGRAM_FOLDER_24,
  IMAGE_PROGRAM_FOLDER_16,
  IMAGE_DOCUMENTS_24,
  IMAGE_SETTINGS_24,
  IMAGE_FIND_24,
  IMAGE_HELP_24,
  IMAGE_RUN_24,
  IMAGE_SHUT_DOWN_24,
  IMAGE_MAIL_16,
  IMAGE_MSDOS_16,
  IMAGE_MSN_16,
  IMAGE_EXPLORER_16,
  IMAGE_CALCULATOR_16,
  IMAGE_NOTEPAD_16,
  IMAGE_PAINT_16,
  IMAGE_WORDWIZ_16,
  __IMAGE_COUNT
} image_id_t;

typedef enum {
  STYLE_STANDARD_DIALOG = 0,
  STYLE_BUTTON,
  STYLE_LIGHT_YELLOW,
  STYLE_GRAY_DITHER,
  STYLE_INNER_BEVEL_NO_FILL,
  STYLE_FILES_CONTENT_BEVEL,
  STYLE_SCROLL_BUTTON,
  __STYLE_COUNT
} style_id_t;

void*
get_font(font_id_t);

void*
get_color(color_id_t);

void*
get_image(image_id_t);

void*
get_style(style_id_t);

#endif
